### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Vladusas** [fabiocogno/nethunter-jfltexx-los16#1]
make O=../kernel clean returns error /usr/bin/env: 'python': No such file or directory
![img](https://user-images.githubusercontent.com/75158945/210592371-855aa3d7-0c27-417d-8bd9-87d103b1318a.png)

**Comment by ImK62** [comment]
Install the build packages

Several packages are needed to build LineageOS. You can install these using your distribution’s package manager.

To build LineageOS, you’ll need:

    bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick
    lib32ncurses5-dev lib32readline-dev lib32z1-dev libelf-dev liblz4-tool libncurses5 libncurses5-dev
    libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync
    schedtool squashfs-tools xsltproc
    zip zlib1g-dev

For Ubuntu versions older than 20.04 (focal), install also:

    libwxgtk3.0-dev

While for Ubuntu versions older than 16.04 (xenial), install:

    libwxgtk2.8-dev

Java

Different versions of LineageOS require different JDK (Java Development Kit) versions.

    LineageOS 18.1+: OpenJDK 11 (included in source download)
    LineageOS 16.0-17.1: OpenJDK 1.9 (included in source download)
    LineageOS 14.1-15.1: OpenJDK 1.8 (install openjdk-8-jdk)
    LineageOS 11.0-13.0: OpenJDK 1.7 (install openjdk-7-jdk)*

* Ubuntu 16.04 and newer do not have OpenJDK 1.7 in the standard package repositories. See the Ask Ubuntu question “[How do I install openjdk 7 on Ubuntu 16.04 or higher?](http://askubuntu.com/questions/761127/how-do-i-install-openjdk-7-on-ubuntu-16-04-or-higher)”. Note that the suggestion to use PPA openjdk-r is outdated (the PPA has never updated their offering of openjdk-7-jdk, so it lacks security fixes); skip that answer even if it is the most upvoted.
Python

For building LineageOS 17.1 and above, you will need python3 as your system`s default. You can check this by calling python --version.

If you are building any of the older branches, python2 is required instead. There are various methods to using it, e.g. [symlinking it manually](https://stackoverflow.com/a/66129356) or creating a [virtualenv](https://pypi.org/project/virtualenv/) for it. We recommend the latter:

Generate the virtualenv once using virtualenv --python=python2 ~/.lineage_venv. Afterwards, activate it in each terminal where you need python2 as default by running ~/.lineage_venv/bin/activate.

The path ~/.lineage_venv can be chosen freely, this is just an example!
